---
title: "Data Cleaning"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(dplyr)
library(tidyr)
library(readr)
```

```{r, message=T}
catch_original<- read_csv("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1")
```

```{r}
catch_data <- catch_original %>%
  select(Region, Year, Chinook, Sockeye, Coho, Pink, Chum) # you can also use select(Region:Chum) or select(-all, -notesRegCode)
```

```{r}
catch_clean <- catch_data %>% 
  mutate(Chinook = as.numeric(Chinook))
```

```{r}
catch_clean <- catch_data %>% 
  mutate(Chinook = ifelse(Chinook == "I", 1, Chinook)) %>% 
  mutate(Chinook = as.numeric((Chinook)))
``` 

```{r}
catch_long <- catch_clean %>% 
  pivot_longer(cols = -c(Region, Year), names_to = "species", values_to = "catch")

catch_wide <- catch_long %>% 
  pivot_wider(names_from = "species", values_from = "catch")
```


```{r}
catch_long <- catch_long %>%
  rename(catch_thousands = catch)

catch_long <- catch_long %>% 
  mutate(catch = catch_thousands*1000) %>%  # mutate can modify or create new columns
  select(-catch_thousands)
```

```{r}
mean_region <- catch_long %>% 
  group_by(Region) %>% 
  summarise(catch_mean = mean(catch)) %>% 
  arrange(desc(catch_mean))

n_region <- catch_long %>% 
  group_by(Region) %>% 
  summarise(n = n())
```

```{r}
SEE_catch <- catch_long %>% 
  filter(Region == "SSE")
```


```{r}
region_defs <- read_csv("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.303.1") %>% 
    select(code, mgmtArea)

catch_joined <- left_join(catch_long, region_defs, by = c("Region" = "code"))

```